export const adminDetails =  {
    content: [
        {
            id: 1,
            first_name: 'Admin',
            last_name: 'Admin',
            middle_name: 'Admin',
            phone_number: '87075000434',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
        },
        {
            id: 2,
            first_name: 'Admin',
            last_name: 'Admin',
            middle_name: 'Admin',
            phone_number: '87075000434',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
        },
        {
            id: 3,
            first_name: 'Admin',
            last_name: 'Admin',
            middle_name: 'Admin',
            phone_number: '87075000434',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
        },
        {
            id: 4,
            first_name: 'Admin',
            last_name: 'Admin',
            middle_name: 'Admin',
            phone_number: '87075000434',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
        },
        {
            id: 5,
            first_name: 'Admin',
            last_name: 'Admin',
            middle_name: 'Admin',
            phone_number: '87075000434',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
        },
        {
            id: 6,
            first_name: 'Admin',
            last_name: 'Admin',
            middle_name: 'Admin',
            phone_number: '87075000434',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
        },
        {
            id: 7,
            first_name: 'Admin',
            last_name: 'Admin',
            middle_name: 'Admin',
            phone_number: '87075000434',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
        },
        {
            id: 8,
            first_name: 'Admin',
            last_name: 'Admin',
            middle_name: 'Admin',
            phone_number: '87075000434',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
        },
        {
            id: 9,
            first_name: 'Admin',
            last_name: 'Admin',
            middle_name: 'Admin',
            phone_number: '87075000434',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
        },
        {
            id: 10,
            first_name: 'Admin',
            last_name: 'Admin',
            middle_name: 'Admin',
            phone_number: '87075000434',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
        },
    ],
    number: 1,
    number_of_elements: 10,
    total_elements: 10,
    total_pages: 1,
}

export const adminInitialValues = [
    {
        name: 'name',
        value: ''
    },
];