export const teacherDetails =  {
    content: [
        {
            id: 1,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            state: 'active',
        },
        {
            id: 2,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            state: 'active',
        },
        {
            id: 3,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 4,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 5,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 6,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 7,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 8,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 9,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 10,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 11,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 12,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 13,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 14,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },
        {
            id: 15,
            first_name: 'Арман',
            last_name: 'Даулетов',
            middle_name: 'Ермекович',
            position: 'Lecturer',
            email: 'test@gmail.com',
            created_date: '2023-03-06 12:00',
            updated_date: '2023-03-06 12:00',
            created_by: 'admin',
            updated_by: 'admin',
            state: 'active',
        },

    ],
    number: 1,
    number_of_elements: 10,
    total_elements: 15,
    total_pages: 2,
}

export const teacherInitialValues = [
    {
        name: 'name',
        value: ''
    },
];
